name: CICD to AWS S3

on:
  push:
    branches:
    - main

jobs:
  deploy:
  runs-on: ubuntu-latest
  steps: 
  - uses: actions/checkout@master
  - uses: jakejarvis/s3-sync-action@master
  with:
    args: --acl public-read --follow-symlinks  --delete
  env:
    AWS_S3_BUCKET: 'resumechallange'
    AWS_REGION: 'us-east-1'
    SOURCE_DIR: 'client'
